name: Development builds CI
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build-windows:
    name: "Create Windows development builds"
    runs-on: "windows-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Create builds
        run: npm run build:windows
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: viper-windows-builds
          path: |
            dist/*.exe
  build-linux:
    name: "Create Linux development builds"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Create builds
        run: npm run build:linux
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: viper-linux-builds
          path: |
            dist/*.AppImage
            dist/*.tar.gz
            dist/*.deb
            dist/*.rpm
